export const actionTypes = {
  ADD_COMMENT: 'ADD_COMMENT',
  SELECT_COMMENT: 'SELECT_COMMENT',
  EDIT_COMMENT: 'EDIT_COMMENT',
  UPDATE_COMMENT: 'UPDATE_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
};
